# See argocd/platform-root.yaml for overrides
clusterRouterDomain: example.cluster.com

gitHost: https://github.com
gitOrg: rohat-access
gitRef: main
gitToken: ghp_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

authClientSecret: replaceme
authSessionSecret: replaceme
